# This is a basic workflow to help you get started with Actions

name: TranquilUnitTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, temp ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unittest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        echo "------------------"
        echo $GITHUB_WORKSPACE
        whoami
        sudo -l
        pwd
        ls -l
        echo "------------------"
        echo test, and deploy your project.

    - name: Testing Get-Tranquil
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Update-Tranquil -Verbose" | pwsh

    - name: Testing New-Tranquil Basic
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; New-TranquilPackage -Verbose ./examples/tranquil-easypackage" | pwsh

    - name: Testing Get-Tranquil
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Install-TranquilPackage -Verbose tranquil-easypackage*" | pwsh

    - name: Testing Get-Tranquil Return testpackage
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Get-TranquilPackage -Verbose tranquil-easypackage" | pwsh

    - name: Testing Get-Tranquil Return testpackage short
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Get-TranquilPackage -Verbose easypack" | pwsh

    - name: Testing Get-Tranquil Return testpackage multiple
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Get-TranquilPackage -Verbose easypack, something-else" | pwsh

    - name: Testing Get-Tranquil Return All
      run: echo "Import-Module -Force ./PowerShellModules/Tranquil; Get-TranquilPackage -Verbose " | pwsh


